name: unit-tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: make install
    - run: make jest
    - run: make lint
    - name: Test & publish code coverage   
      uses:  paambaati/codeclimate-action@v2.5.7
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_SAE }}
      with:
          coverageCommand: make test-coverage
          debug: true